#!/bin/bash

#

file_base=$1

log=${file_base}.pipeline.log


# bracket to redirect all stdout output to log file
{

f1=${file_base}_R1_fu.fastq
f2=${file_base}_R2_fu.fastq

echo "*************************"
echo "filtering out mouse seqs "
echo "*************************"

# this is a database of the mm10 mouse genome assembly
btindex=/home/databases/mouse/mm10

num_cpu=8
output_suffix=mm_genome

# unpaired
bowtie2 -x $btindex --local -q -U $f1 --sensitive --score-min C,60,0 --time -p $num_cpu -S ${f1}.${output_suffix}_bt.sam 2> ${f1}.${output_suffix}_bt.log

fasta_from_sam -f $f1 -r ${f1}.mm_genome_bt.sam > ${file_base}_R1_fuh1.fastq

reconcile_read2_file ${file_base}_R1_fuh1.fastq ${file_base}_R2_fu.fastq f2 > ${file_base}_R2_fuh1.fastq

f2=${file_base}_R2_fuh1.fastq
bowtie2 -x $btindex --local -q -U $f2 --sensitive --score-min C,60,0 --time -p $num_cpu -S ${f2}.${output_suffix}_bt.sam 2> ${f2}.${output_suffix}_bt.log

f2_sam=${file_base}_R2_fuh1.fastq.mm_genome_bt.sam

fasta_from_sam -f ${file_base}_R2_fuh1.fastq -r $f2_sam > ${file_base}_R2_fuh.fastq

reconcile_read2_file ${file_base}_R2_fuh.fastq ${file_base}_R1_fuh1.fastq > ${file_base}_R1_fuh.fastq


} 2>&1  | tee -a $log  # output tee'd to a logfile



