#!/bin/bash

#
# This script filters tick sequences from a sequencing dataset by
# alignment to the I scapularis genome sequence
#
# It is meant to work in the context of our lab's overall taxonomy pipeline
#
# Input: the file base name (file_base)
#
# The script expects a single end read fastq file named:
# 
#       ${file_base}_R1_fu.fastq
#
# E.g., my_sample_R1_fu.fastq    
#
# The _fu  in the filenames indicate that they have been quality filtered (f) and collapsed
# to unique sequences (u).
#
# The script uses bowtie2 to align the reads in these files against the tick genome
# and produces a file that contains all the non-aligning reads.  This file has an _fuh suffix
# to indicate that it has been host filtered(h)
#
# E.g., my_sample_R1_fuh.fastq    
#
#
# Dependencies: 
#
# (*) bowtie2 must be installed.  
#
# (*) This script calls other scripts, which should be in the user's PATH
# 
#
#
#    Mark Stenglein 
#    March, 2016
#
#

file_base=$1

log=${file_base}.pipeline.log

# ---------------------
# Modifiable parameters
# ---------------------

# Location of bowtie2 index of genome
btindex=/home/databases/tick/tick_genome

# output suffix of files created
output_suffix=tick_genome

# num_cpu for running bowtie2
num_cpu=12

# minimum alignment score
# a score of 60 corresponds to approximately a perfect match over 30 nt
min_score=60


# bracket to redirect all stderr and stdout output to log file
{

f1=${file_base}_R1_fu.fastq

echo "*****************************************************"
echo "filtering out I. scapularis seqs from file $f1 "
echo "*****************************************************"

# align R1 reads
echo "bowtie2 -x $btindex --local -q -U $f1 --sensitive --score-min C,${min_score},0 --time --un ${file_base}_R1_fuh.fastq -p $num_cpu -S ${f1}.${output_suffix}_bt.sam 2> ${f1}.${output_suffix}_bt.log"
bowtie2 -x $btindex --local -q -U $f1 --sensitive --score-min C,${min_score},0 --time --un ${file_base}_R1_fuh.fastq -p $num_cpu -S ${f1}.${output_suffix}_bt.sam 2> ${f1}.${output_suffix}_bt.log


} 2>&1  | tee -a $log  # output tee'd to a logfile



