#!/bin/bash

ids_file="$1"

while read -r line
do
   id="$line"

	# Illumina replaces _ and . with - for some annoying reason

	butchered_id=${id}
	# butchered_id=${id//_/-}
	butchered_id=${butchered_id//./-}

	matching_files=`ls ${butchered_id}_*R1*fastq | wc -l`
	if [[ $matching_files -ne 1 ]]
	then
	   echo "error: no match for id $butchered_id ($id)"
	   echo "$matching_files matches"
		exit
	fi
	r1_file=`ls ${butchered_id}_*R1*.fastq`
	echo "mv $r1_file ${id}_R1.fastq"
	# mv $r1_file ${id}_R1.fastq

	matching_files=`ls ${butchered_id}_*R2*fastq | wc -l`
	if [[ $matching_files -ne 1 ]]
	then
	   echo "error: no match for id $butchered_id ($id)"
	   echo "$matching_files matches"
		exit
	fi
	r2_file=`ls ${butchered_id}_*R2*.fastq`
	echo "mv $r2_file ${id}_R2.fastq"
	# mv $r2_file ${id}_R2.fastq

done < "$ids_file"
