#!/bin/bash

f1=$1
f2=$2

f=$f1

bt_index=$3
index_name=${bt_index##/*/}
output_prefix=${f}.${index_name}.paired

log_f=${output_prefix}.bt_log

# this_file=`basename $0`
# cp $this_file ${this_file}

cmd="bowtie2 
 -x $bt_index
 -q
 -1 $f1 
 -2 $f2
 --rg-id 1
 --rg SM:1
 --local
 --qc-filter
 --score-min C,120,1
 --no-unal
 --maxins 700
 --time
 --al-conc ${output_prefix}.conc_hits.fastq
 --threads 24
 -S ${output_prefix}.sam"

echo $cmd
echo $0 $* > $log_f
echo $cmd >> $log_f
$cmd 2>> $log_f

# process output
samtools view -S -b ${output_prefix}.sam > ${output_prefix}.bam
samtools sort ${output_prefix}.bam > ${output_prefix}_sorted.bam
samtools index ${output_prefix}_sorted.bam
samtools depth ${output_prefix}_sorted.bam > ${output_prefix}.depth
