#!/usr/bin/env bash

# This helper script will map _fuh.fastq files (quality and host-filtered paired read files 
# from the Stenglein lab taxonomy pipeline) to some bowtie index
#
# Usage: ./run_bt_fuh_paired <sample_id> <bt_index>
#
# Mark Stenglein 2015

sample_id=$1
index=$2

# fastq file names
f1=${sample_id}_R1_fuh.fastq
f2=${sample_id}_R2_fuh.fastq

# run via helper script
./run_bt_paired $f1 $f2 $index

