#!/usr/bin/env bash

# This helper script will map a _fuh.fastq file (quality and host-filtered single end read file
# from the Stenglein lab taxonomy pipeline) to some bowtie index
#
# Usage: ./run_bt_fuh_paired <sample_id> <bt_index>
#
# Mark Stenglein 2015


sample_id=$1
index=$2

# the fastq filename
f1=${sample_id}_R1_fuh.fastq

# use the other helper script
./run_bt $f1 $index

