#!/bin/bash -x

# This script creates a SQLite3 database that maps 
# NCBI nucleotide and protein sequence accessions to NCBI taxids

# The data is imported from nucl_gb.accession2taxid and prot.accession2taxid 
# files available at: https://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/ 

# get rid of old temporary db if it exists
rm -f ncbi_taxonomy.sqlite3.temp

sqlite3 -batch ncbi_taxonomy.sqlite3.temp <<"EOF"

CREATE TABLE acc_taxid_map (
  'acc' char(12) primary key,
  'acc_ver' char(15), 
  'taxid' integer,
  'gi' integer 
);

.separator "\t"

-- populate table by importing nucl accession -> taxid map
.import nucl_gb.accession2taxid acc_taxid_map

-- get rid of record corresponding to header row
delete from acc_taxid_map where acc = 'accession';

-- populate table by importing protein accession -> taxid map
.import prot.accession2taxid acc_taxid_map

-- get rid of record corresponding to header row
delete from acc_taxid_map where acc = 'accession';

EOF

# overwrite db with temp db
mv ncbi_taxonomy.sqlite3.temp ncbi_taxonomy.sqlite3


