#!/bin/bash -x

# This script creates a sqlite database from the NCBI Taxonomy database's nodes.dmp file
# 
# According to this document: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_readme.txt
#
# nodes.dmp consists of the following fields, separated by "|" characters
#
#     nodes.dmp
#     ---------
#     
#     This file represents taxonomy nodes. The description for each node includes 
#     the following fields:
#     
#     	tax_id					-- node id in GenBank taxonomy database
#      	parent tax_id				-- parent node id in GenBank taxonomy database
#      	rank					-- rank of this node (superkingdom, kingdom, ...) 
#      	embl code				-- locus-name prefix; not unique
#      	division id				-- see division.dmp file
#      	inherited div flag  (1 or 0)		-- 1 if node inherits division from parent
#      	genetic code id				-- see gencode.dmp file
#      	inherited GC  flag  (1 or 0)		-- 1 if node inherits genetic code from parent
#      	mitochondrial genetic code id		-- see gencode.dmp file
#      	inherited MGC flag  (1 or 0)		-- 1 if node inherits mitochondrial gencode from parent
#      	GenBank hidden flag (1 or 0)            -- 1 if name is suppressed in GenBank entry lineage
#      	hidden subtree root flag (1 or 0)       -- 1 if this subtree has no sequence data yet
#      	comments				-- free-text comments and citations
# 
#  


# get rid of old temporary db if it exists
rm -f nodes_dmp.sqlite3.temp

# we really only care about the first 3 columns of data so don't import the rest for now.
# First, extract those 3 columns and convert | to tabs 
rm -f nodes.dmp.col_1_to_3
cat nodes.dmp | perl -p -e 's/\t\|\t/\t/g' | cut -f 1-3 > nodes.dmp.col_1_to_3

# create the sqlite table and populate it with data from 
sqlite3 -batch nodes_dmp.sqlite3.temp <<"EOF"

CREATE TABLE nodes_dmp (
  taxid integer primary key,
  parent_taxid integer,
  rank text
);

.mode tabs

-- populate table by importing processed nodes.dmp -> nodes_dmp table
.import nodes.dmp.col_1_to_3 nodes_dmp

EOF

# overwrite working db with temp db ?
mv nodes_dmp.sqlite3.temp nodes_dmp.sqlite3




