#!/usr/bin/env perl

use strict;
use Getopt::Long;
use Data::Dumper;

# allow use of modules in pwd
use Cwd 'abs_path';
use File::Basename;
use lib dirname( abs_path $0 );

use taxid_info;

my $print_usage = 0;

my $db_path = "/home/databases/NCBI_Taxonomy/nodes_dmp.sqlite3";

my $usage = <<USAGE;

  This script tests retreival of info about NCBI taxids: their descendent taxids, parent taxid, ankd rank

  This mapping is accomplished via a SQLite database containing info from the NCBI nodes.dmp file

  This database is created using:
  https://github.com/stenglein-lab/taxonomy_pipeline/blob/main/scripts/download_and_process_taxonomy_databases 

  The location of this database can be specified using the -db command-line option.

  Mark Stenglein,  3/27/2023

  Usage: $0 [-h] [-db db_path] 

   [-h]          Print this message

   [-db db_path] The path to a SQlite database containing acc->taxid mapping
                 (default: $db_path)

USAGE

if (! -e $db_path)
{
  die("ERROR: db_path: $db_path does not exist.\n");
}

print "Flavivirus genus: taxid 11051\n";
my $taxid = 11051;

print "flavi child taxids:\n";
my $flavi_descendents = taxid_info::taxid_descendents($db_path, $taxid);
print Dumper(@$flavi_descendents);

print "\nHomo sapiends: taxid 96060\n";
$taxid = 9606;

print "Human child taxids:\n";
my $human_descendents = taxid_info::taxid_descendents($db_path, $taxid);
print Dumper(@$human_descendents);

print "\nflavi child taxids:\n";
print Dumper(@$flavi_descendents);

print "\nHuman child taxids:\n";
print Dumper(@$human_descendents);
